# Generated by Django 2.2.3 on 2019-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionPaperDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=10, null=True, verbose_name='sub_code')),
                ('qno', models.IntegerField(null=True, verbose_name='questionNo')),
                ('sqno', models.IntegerField(null=True, verbose_name='numberofSubquestions')),
                ('a', models.IntegerField(null=True, verbose_name='a')),
                ('b', models.IntegerField(null=True, verbose_name='b')),
                ('c', models.IntegerField(null=True, verbose_name='c')),
                ('d', models.IntegerField(null=True, verbose_name='d')),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engg.'), ('MH', 'Mechanical Engg.'), ('CV', 'Civil Engg.'), ('ISE', 'Information science and Engg.'), ('ECE', 'Electronics and Communication and Engg.'), ('EEE', 'Electrical and Electronics Engg.'), ('EIE', 'Electronics and Instrumentation Engg.'), ('TC', 'Telecommunication Engg.'), ('BT', 'Biotechnology Engg.'), ('CH', 'Chemical Engg.'), ('IEM', 'Industrial Engg. and Management')], max_length=40, null=True, verbose_name='Branch')),
                ('semester', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], max_length=5, null=True, verbose_name='semester')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('MH', 'Mech'), ('CV', 'Civil'), ('ISE', 'Information Science'), ('EC', 'Electronics and Communication'), ('EEE', 'Electronics and Electrical'), ('TC', 'Telecommunication')], max_length=50, null=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='semester',
            field=models.CharField(max_length=2, verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_code',
            field=models.CharField(max_length=10, verbose_name='sub_code'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_name',
            field=models.CharField(max_length=50, verbose_name='sub_name'),
        ),
    ]
