# Generated by Django 2.2.3 on 2019-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190813_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='semester',
            field=models.CharField(max_length=5, verbose_name='semester'),
        ),
    ]
