# Generated by Django 2.2.3 on 2019-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190816_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaperdetails',
            name='a',
            field=models.IntegerField(default=0, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='questionpaperdetails',
            name='b',
            field=models.IntegerField(default=0, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='questionpaperdetails',
            name='c',
            field=models.IntegerField(default=0, null=True, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='questionpaperdetails',
            name='d',
            field=models.IntegerField(default=0, null=True, verbose_name='d'),
        ),
    ]
