# Generated by Django 2.2.3 on 2020-01-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190818_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperdetails',
            name='slNo',
            field=models.IntegerField(max_length=3, null=True, verbose_name='slNo'),
        ),
    ]
