# Generated by Django 2.2.3 on 2020-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_detailed_marks_generatebarcode_tbl_studentmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperdetails',
            name='qno',
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='semid',
            field=models.IntegerField(null=True, verbose_name='SemID'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='studentid',
            field=models.IntegerField(null=True, verbose_name='StudentID'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='sub_id',
            field=models.IntegerField(null=True, verbose_name='SubjectID'),
        ),
    ]
