# Generated by Django 2.2.3 on 2020-02-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200225_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailed_marks',
            old_name='final',
            new_name='FinalTotal',
        ),
    ]
