# Generated by Django 2.2.3 on 2020-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200225_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_marks',
            name='FinalTotal',
            field=models.IntegerField(default=0, verbose_name='FinalTotal'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a1',
            field=models.IntegerField(default=0, null=True, verbose_name='1a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a10',
            field=models.IntegerField(default=0, null=True, verbose_name='10a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a2',
            field=models.IntegerField(default=0, null=True, verbose_name='2a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a3',
            field=models.IntegerField(default=0, null=True, verbose_name='3a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a4',
            field=models.IntegerField(default=0, null=True, verbose_name='4a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a5',
            field=models.IntegerField(default=0, null=True, verbose_name='5a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a6',
            field=models.IntegerField(default=0, null=True, verbose_name='6a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a7',
            field=models.IntegerField(default=0, null=True, verbose_name='7a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a8',
            field=models.IntegerField(default=0, null=True, verbose_name='8a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='a9',
            field=models.IntegerField(default=0, null=True, verbose_name='9a'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b1',
            field=models.IntegerField(default=0, null=True, verbose_name='1b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b10',
            field=models.IntegerField(default=0, null=True, verbose_name='10b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b2',
            field=models.IntegerField(default=0, null=True, verbose_name='2b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b3',
            field=models.IntegerField(default=0, null=True, verbose_name='3b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b4',
            field=models.IntegerField(default=0, null=True, verbose_name='4b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b5',
            field=models.IntegerField(default=0, null=True, verbose_name='5b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b6',
            field=models.IntegerField(default=0, null=True, verbose_name='6b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b7',
            field=models.IntegerField(default=0, null=True, verbose_name='7b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b8',
            field=models.IntegerField(default=0, null=True, verbose_name='8b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='b9',
            field=models.IntegerField(default=0, null=True, verbose_name='9b'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c1',
            field=models.IntegerField(default=0, null=True, verbose_name='1c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c10',
            field=models.IntegerField(default=0, null=True, verbose_name='10c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c2',
            field=models.IntegerField(default=0, null=True, verbose_name='2c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c3',
            field=models.IntegerField(default=0, null=True, verbose_name='3c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c4',
            field=models.IntegerField(default=0, null=True, verbose_name='4c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c5',
            field=models.IntegerField(default=0, null=True, verbose_name='5c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c6',
            field=models.IntegerField(default=0, null=True, verbose_name='6c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c7',
            field=models.IntegerField(default=0, null=True, verbose_name='7c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c8',
            field=models.IntegerField(default=0, null=True, verbose_name='8c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='c9',
            field=models.IntegerField(default=0, null=True, verbose_name='9c'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d1',
            field=models.IntegerField(default=0, null=True, verbose_name='1d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d10',
            field=models.IntegerField(default=0, null=True, verbose_name='10d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d2',
            field=models.IntegerField(default=0, null=True, verbose_name='2d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d3',
            field=models.IntegerField(default=0, null=True, verbose_name='3d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d4',
            field=models.IntegerField(default=0, null=True, verbose_name='4d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d5',
            field=models.IntegerField(default=0, null=True, verbose_name='5d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d6',
            field=models.IntegerField(default=0, null=True, verbose_name='6d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d7',
            field=models.IntegerField(default=0, null=True, verbose_name='7d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d8',
            field=models.IntegerField(default=0, null=True, verbose_name='8d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='d9',
            field=models.IntegerField(default=0, null=True, verbose_name='9d'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='max1',
            field=models.IntegerField(default=0, null=True, verbose_name='MaxTotal1'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='max2',
            field=models.IntegerField(default=0, null=True, verbose_name='MaxTotal2'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='max3',
            field=models.IntegerField(default=0, null=True, verbose_name='MaxTotal3'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='max4',
            field=models.IntegerField(default=0, null=True, verbose_name='MaxTotal4'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='max5',
            field=models.IntegerField(default=0, null=True, verbose_name='MaxTotal5'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total1',
            field=models.IntegerField(default=0, null=True, verbose_name='Total1'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total10',
            field=models.IntegerField(default=0, null=True, verbose_name='Total10'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total2',
            field=models.IntegerField(default=0, null=True, verbose_name='Total2'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total3',
            field=models.IntegerField(default=0, null=True, verbose_name='Total3'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total4',
            field=models.IntegerField(default=0, null=True, verbose_name='Total4'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total5',
            field=models.IntegerField(default=0, null=True, verbose_name='Total5'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total6',
            field=models.IntegerField(default=0, null=True, verbose_name='Total6'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total7',
            field=models.IntegerField(default=0, null=True, verbose_name='Total7'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total8',
            field=models.IntegerField(default=0, null=True, verbose_name='Total8'),
        ),
        migrations.AlterField(
            model_name='detailed_marks',
            name='total9',
            field=models.IntegerField(default=0, null=True, verbose_name='Total9'),
        ),
    ]
