# Generated by Django 2.2.3 on 2020-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200225_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperdetails',
            name='qno',
            field=models.IntegerField(null=True, verbose_name='qno'),
        ),
    ]
