# Generated by Django 2.2.3 on 2020-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_questionpaperdetails_qno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_marks',
            name='c1',
            field=models.IntegerField(default=0, null=True, verbose_name='1c'),
        ),
    ]
