# Generated by Django 2.2.3 on 2020-03-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200226_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_marks',
            name='Evaluator',
            field=models.IntegerField(null=True, verbose_name='Evaluator'),
        ),
    ]
