# Generated by Django 2.2.3 on 2020-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_detailed_marks_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sub_code',
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_id',
            field=models.CharField(default=0, max_length=10, verbose_name='sub_id'),
            preserve_default=False,
        ),
    ]
