# Generated by Django 2.2.3 on 2020-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200306_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatebarcode',
            old_name='sem_id',
            new_name='semid',
        ),
        migrations.RemoveField(
            model_name='questionpaperdetails',
            name='sub_code',
        ),
        migrations.AddField(
            model_name='questionpaperdetails',
            name='sub_id',
            field=models.IntegerField(null=True, verbose_name='sub_id'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_id',
            field=models.IntegerField(null=True, verbose_name='sub_id'),
        ),
    ]
