# Generated by Django 2.2.3 on 2020-03-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200306_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperdetails',
            name='sem_id',
            field=models.IntegerField(null=True, verbose_name='sem_id'),
        ),
    ]
